// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title IOvaReferral Interface
/// @notice Interface for the OVA referral system that tracks referrals and rewards
interface IOvaReferral {
    /// @notice Get the address that referred a user
    /// @param user The address of the user to check
    /// @return The address that referred the user, or zero address if not referred
    function referredFrom(address user) external view returns (address);

    /// @notice Get the address associated with a referral code
    /// @param code The referral code to look up
    /// @return The address that created this referral code
    function referralCodes(string memory code) external view returns (address);

    /// @notice Get all addresses referred by a user
    /// @param user The address to check referrals for
    /// @return Array of addresses that were referred by this user
    function seeReferred(address user) external view returns (address[] memory);

    /// @notice Get the total points generated by a user through referrals
    /// @param user The address to check points for
    /// @return The total number of points generated
    function generatedPoints(address user) external view returns (uint256);

    /// @notice Track points for a referral action
    /// @param user The address to track points for
    /// @param amount The amount of points to add
    function track(address user, uint256 amount) external;

    /// @notice Use a referral code to establish a referral relationship
    /// @param code The referral code to consume
    function consumeReferral(string memory code) external;
}
