// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title IOverlayerReferral Interface
/// @notice Interface for the Overlayer referral system that tracks referrals and rewards
interface IOverlayerReferral {
    /// @notice Referral code / relationship type
    enum ReferralType {
        None,
        Team,
        Ref
    }

    /// @notice Get the address that referred a user for a given type
    /// @param user The address of the user to check
    /// @param type_ The referral type
    /// @return The address that referred the user for that type, or zero if not referred
    function referredFromByType(
        address user,
        ReferralType type_
    ) external view returns (address);

    /// @notice Get the address associated with a referral code
    /// @param code The referral code to look up
    /// @return The address that created this referral code
    function referralCodes(string memory code) external view returns (address);

    /// @notice Get the type associated with a referral code
    /// @param code The referral code to look up
    /// @return The referral type of the code
    function referralCodeTypes(
        string memory code
    ) external view returns (ReferralType);

    /// @notice Get the code created by a holder for a given type
    /// @param holder The code holder
    /// @param type_ The referral type
    /// @return The referral code, or empty if none
    function referralCodesByType(
        address holder,
        ReferralType type_
    ) external view returns (string memory);

    /// @notice Get all addresses referred by a user for a given type
    /// @param user The address to check referrals for
    /// @param type_ The referral type
    /// @return Array of addresses that were referred by this user for that type
    function seeReferredByType(
        address user,
        ReferralType type_
    ) external view returns (address[] memory);

    /// @notice Get points generated by a user for a referral type
    /// @param user The address to check points for
    /// @param type_ The referral type
    /// @return Points generated for that type
    function generatedPointsByType(
        address user,
        ReferralType type_
    ) external view returns (uint256);

    /// @notice Get total points generated by a user (Team + Ref)
    /// @param user The address to check points for
    /// @return The sum of points across referral types
    function generatedPoints(address user) external view returns (uint256);

    /// @notice Whether a team is open for anyone to join
    /// @param owner_ The team owner
    /// @return True if the team is open
    function isTeamOpen(address owner_) external view returns (bool);

    /// @notice Whether a member is on a team's whitelist
    /// @param owner_ The team owner
    /// @param member_ The candidate member
    /// @return True if whitelisted
    function isTeamWhitelisted(
        address owner_,
        address member_
    ) external view returns (bool);

    /// @notice Whether a consumer can join a team (open or whitelisted)
    /// @param owner_ The team owner
    /// @param consumer_ The candidate consumer
    /// @return True if join is allowed
    function canJoinTeam(
        address owner_,
        address consumer_
    ) external view returns (bool);

    /// @notice Track points for a referral action of a given type
    /// @param user The address to track points for
    /// @param amount The amount of points to add
    /// @param type_ The referral type the points belong to
    function track(address user, uint256 amount, ReferralType type_) external;

    /// @notice Use a referral code to establish a referral relationship
    /// @param code The referral code to consume
    function consumeReferral(string memory code) external;
}
